version: '3.4'

services:
  mshroo3ireactspa:
    image: mshroo3ireactspa
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000
